# Activation Functions

###  ReLU Activation Function

In [ ]:
import numpy as np
np.random.seed(0)

X = [
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = []

for i in inputs:
    output.append(max(0, i))

print(output)


# output = np.maximum(0, inputs) # numpy function equivalent to max()
# print(output)


[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [12]:
class ReLU:

    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

### Softmax activation

In [3]:
# take sample output from previos layers
layer_outputs = [4.8, 1.21, 2.385]

# e - mathematical constant
e = 2.71828182846

# For each value in a vector, calculate the exponential value
exp_values = []
for output in layer_outputs:
    exp_values.append(e ** output)

print("Exponentiated values: ", exp_values)

# Now normalize values
norm_base = sum(exp_values)
norm_values = []
for value in exp_values:
    norm_values.append(value / norm_base)

print("Normalized exponentiated values: ", norm_values)

# To verify, check if the sum of norm_values is 1 or not.
print("Sum of normalized values: ", sum(norm_values))

Exponentiated values:  [121.51041751893969, 3.3534846525504487, 10.85906266492961]
Normalized exponentiated values:  [0.8952826639573506, 0.024708306782070668, 0.08000902926057876]
Sum of normalized values:  1.0


In [ ]:
# Using numpy for faster calculation

import numpy as np

layer_outputs = [4.8, 1.21, 2.385]

exp_values = np.exp(layer_outputs)
norm_values = exp_values / np.sum(exp_values)

print(f"Normalized exponential values: {norm_values}")
print(f"Sum of normalized values: {sum(norm_values)}")

Normalized exponential values: [0.89528266 0.02470831 0.08000903]
Sum of normalized values: 0.9999999999999999


In [4]:
class Softmax:

    def forward(self, inputs):
        # Get unnormalized probabilities
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))

        # Normalize them for each sample
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)

        self.output = probabilities

## Combining everything up to this point:

In [ ]:
import numpy as np # type: ignore
from nnfs.datasets import spiral_data   # type: ignore
import nnfs # type: ignore

nnfs.init()

# Dense Layer
class Layer_Dense:

    # Layer initialization
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    # Forward Pass
    def forward(self, inputs):
        # Calculate output values from inputs, weights and biases
        self.output = np.dot(inputs, self.weights) + self.biases


class ReLU:
    
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Softmax:

    def forward(self, inputs):
        # Get unnormalized probabilities
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))

        # Normalize them for each sample
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)

        self.output = probabilities


# Create dataset
X, y = spiral_data(samples = 100, classes = 3)

# Create Dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)

# Create ReLU activation (to be used with Dense layer)
activation1 = ReLU()

# Create second Dense layer with 3 input features (as we take output of previous layer here) and 3 output values
dense2 = Layer_Dense(3, 3)

# Create Softmax activation (to be used with Dense layer)
activation2 = Softmax()

# Make a forward pass of our training data through this layer
dense1.forward(X)

# Make a forward pass through activation function
# It takes the output of first dense layer
activation1.forward(dense1.output)

# Make a forward pass through second Dense layer
# It takes outputs of activation function of first layer as inputs
dense2.forward(activation1.output)

# Make a forward pass through activation function
# It takes in output of second dense layer
activation2.forward(dense2.output)

# Let's see output of the first few samples
print(activation2.output[0:5])

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
